export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <head>
        <title>NextJS App</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <nav>
          <h1>
            navbar
          </h1>
          <ul>
            <li>
              home
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
